apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: microservices
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 8080        # Service port exposed inside the cluster
      targetPort: 8080  # Container port your app listens on
  type: ClusterIP      # Optional, defaults to ClusterIP (good for internal access)
