apiVersion: v1
kind: Service
metadata:
  name: python-microservice
  labels:
    app: python-microservice
spec:
  selector:
    app: python-microservice
  ports:
    - name: http
      port: 8000
      targetPort: 8000
